from langflow.custom import Component
from langflow.io import Output, StrInput
from langflow.schema import Data
from pptx import Presentation
import tempfile
import base64
import os


class SimplePowerPointComponent(Component):
    display_name = "Simple PowerPoint"
    description = "Creates a simple PowerPoint with one slide containing your text"
    icon = "📊"

    inputs = [
        StrInput(
            name="slide_text",
            display_name="Slide Text",
            info="The text to display on the PowerPoint slide",
            required=True,
            value="Hello from Langflow!"
        )
    ]

    outputs = [
        Output(
            display_name="Response",
            name="response_output",
            method="create_powerpoint"
        )
    ]

    def create_powerpoint(self) -> Data:
        """Create a simple PowerPoint with one slide"""

        try:
            prs = Presentation()

            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)

            title = slide.shapes.title
            title.text = "Generated by Langflow"

            content = slide.placeholders[1]
            content.text = self.slide_text

            temp_file = tempfile.NamedTemporaryFile(suffix='.pptx', delete=False)
            temp_file_path = temp_file.name
            temp_file.close()

            prs.save(temp_file_path)

            with open(temp_file_path, 'rb') as f:
                file_content = f.read()

            os.unlink(temp_file_path)

            base64_content = base64.b64encode(file_content).decode('utf-8')

            filename = "langflow_presentation.pptx"

            text_response = f"""✅ PowerPoint presentation created successfully!

📄 **File:** {filename}
📊 **Content:** "{self.slide_text}"
📏 **Size:** {len(file_content):,} bytes

<GENERATED_PPTX>
filename:{filename}
content_type:application/vnd.openxmlformats-officedocument.presentationml.presentation
size:{len(file_content)}
data:{base64_content}
</GENERATED_PPTX>"""

            return Data(data={"text": text_response})

        except Exception as e:
            error_text = f"❌ Failed to create PowerPoint presentation: {str(e)}"
            return Data(data={"text": error_text})