from langflow.custom import Component
from langflow.io import Output, StrInput
from langflow.schema import Data
from pptx import Presentation
from pptx.util import Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import tempfile
import base64
import os
from dotenv import load_dotenv

load_dotenv()

PPTX_MAGIC_BYTES = os.getenv("PPTX_MAGIC_BYTES")


class SimplePowerPointComponent(Component):
    display_name = "Simple PowerPoint"
    description = "Creates a simple PowerPoint with one slide containing your text"
    icon = "📊"

    inputs = [
        StrInput(
            name="slide_text",
            display_name="Slide Text",
            info="The text to display on the PowerPoint slide",
            required=True,
            value="Hello from Langflow!"
        )
    ]

    outputs = [
        Output(
            display_name="Response",
            name="response_output",
            method="create_powerpoint"
        )
    ]

    def create_powerpoint(self) -> Data:
        """Create a simple PowerPoint with one slide"""

        try:
            prs = Presentation()
            prs.slide_width = int(33.867 * 360000)
            prs.slide_height = int(19.05 * 360000)

            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)

            title = slide.shapes.title
            title.left = int(1.19 * 360000)
            title.top = int(0.81 * 360000)
            title.width = int(31.49 * 360000)
            title.height = int(1.16 * 360000)
            title.text = "Generated by Langflow"
            title_text_frame = title.text_frame
            title_paragraph = title_text_frame.paragraphs[0]
            title_paragraph.alignment = PP_ALIGN.LEFT
            title_run = title_paragraph.runs[0]
            title_run.font.size = Pt(28)
            title_run.font.name = "Biennale Bold"
            title_run.font.color.rgb = RGBColor(0, 115, 230)

            content = slide.placeholders[1]
            content.text = self.slide_text

            temp_file = tempfile.NamedTemporaryFile(suffix='.pptx', delete=False)
            temp_file_path = temp_file.name
            temp_file.close()

            prs.save(temp_file_path)

            with open(temp_file_path, 'rb') as f:
                file_content = f.read()

            os.unlink(temp_file_path)

            base64_content = base64.b64encode(file_content).decode('utf-8')

            filename = "langflow_presentation.pptx"

            text_response = f"""PowerPoint presentation created successfully!

<{PPTX_MAGIC_BYTES}>
filename:{filename}
content_type:application/vnd.openxmlformats-officedocument.presentationml.presentation
size:{len(file_content)}
data:{base64_content}
</{PPTX_MAGIC_BYTES}>"""

            return Data(data={"text": text_response})

        except Exception as e:
            error_text = f"❌ Failed to create PowerPoint presentation: {str(e)}"
            return Data(data={"text": error_text})